### ISSUE TITLE
🐛 Remove hooks from MermaidRenderer

### ISSUE THREAD

**Issue by GYHHAHA** [executablebooks/myst-theme#107]
### Describe the bug

Similar to #96 , we should remove hooks in MermaidRenderer:
https://github.com/executablebooks/myst-theme/blob/e95834a58ae08d3b2a381854aa8fb0d4725ad8d6/packages/diagrams/src/index.tsx#L14

### Reproduce the bug

raise error: Invalid hook call. Hooks can only be called inside of the body of a function component.

**Comment by rowanc1** [comment]
I think something else might be going on, this should be mitigated by the wrapping here:
https://github.com/executablebooks/myst-theme/blob/e95834a58ae08d3b2a381854aa8fb0d4725ad8d6/packages/diagrams/src/index.tsx#L41

The wrapping of the node-renderer should allow react hooks that are added inside of them. Can you show more about where this error is coming from?

**Comment by GYHHAHA** [comment]
Sorry about this. I misread MermaidNodeRenderer as MermaidRenderer. Now it works after changing to MermaidNodeRenderer. Thanks for pointing this out! @rowanc1

**Comment by GYHHAHA** [comment]
However this is another problem: words in the blocks seem to be clipped. It's fine in the myst sindbox.
![29 05 2023_17 08 14_REC](https://github.com/executablebooks/myst-theme/assets/41546976/736c80f0-aae3-4b76-a935-024d79a64db1)

**Comment by rowanc1** [comment]
Hm, haven't seen that before!!

Can you open another issue for that, is that in the book theme, or in your own app?

**Comment by GYHHAHA** [comment]
It's in my own app. And I test book theme locally and it is normal. Thus it's maybe caused some of settings by myself instead of myst, so I probably should not open issue for this now @rowanc1 . But I can provide a minimal example with rendered difference here, mainly difference on height:
````
\`\`\`{mermaid}
flowchart LR
  j
\`\`\`
````
book theme
```html
<g class="root"
  ><g class="clusters"></g><g class="edgePaths"></g><g class="edgeLabels"></g
  ><g class="nodes"
    ><g
      transform="translate(10.43359375, 19.5)"
      id="flowchart-j-2036"
      class="node default default"
      ><rect
        height="39"
        width="20.8671875"
        y="-19.5"
        x="-10.43359375"
        ry="0"
        rx="0"
        style=""
        class="basic label-container"
      ></rect
      ><g transform="translate(-2.93359375, -12)" style="" class="label"
        ><foreignObject height="24" width="5.8671875"
          ><div
            style="display: inline-block; white-space: nowrap"
            xmlns="http://www.w3.org/1999/xhtml"
          >
            <span class="nodeLabel">j</span>
          </div></foreignObject
        ></g
      ></g
    ></g
  ></g
>
```
my app
```html
<g class="root"
  ><g class="clusters"></g><g class="edgePaths"></g><g class="edgeLabels"></g
  ><g class="nodes"
    ><g
      transform="translate(10.43359375, 16.75)"
      id="flowchart-j-56"
      class="node default default"
      ><rect
        height="33.5"
        width="20.8671875"
        y="-16.75"
        x="-10.43359375"
        ry="0"
        rx="0"
        style=""
        class="basic label-container"
      ></rect
      ><g transform="translate(-2.93359375, -9.25)" style="" class="label"
        ><foreignObject height="18.5" width="5.8671875"
          ><div
            style="display: inline-block; white-space: nowrap"
            xmlns="http://www.w3.org/1999/xhtml"
          >
            <span class="nodeLabel">j</span>
          </div></foreignObject
        ></g
      ></g
    ></g
  ></g
>
```
