### ISSUE TITLE
`abstract` block is not rendered out 

### ISSUE THREAD

**Issue by Jan-David-Black** [executablebooks/myst-theme#190]
### Describe the bug

**context**
Following the tutorial here: https://mystmd.org/guide/quickstart-myst-documents
I come to the section on adding an `abstract` block: https://mystmd.org/guide/quickstart-myst-documents#add-an-abstract-block

**expectation**
I expected an output similar to the image shown in the guide.

**bug**
No visual emphasis is present. The Block is rendered out unchanged.

### Reproduce the bug

Follow the tutorial to the abstract block section.

### List your environment

myst
```
mystmd@v1.1.7
```

book-theme:
```
"name": "@myst-theme/book",
"version": "0.4.0",
```

**Comment by Jan-David-Black** [comment]
@rowanc1 not sure whether this is the right placeto post this, feel free to nudge me in the right direction, so that I can improve going forward.

**Comment by rowanc1** [comment]
Thanks for the bug report -- something I have been meaning to do for a while. We had it in the article theme, but hadn't back-ported to the book theme. The screenshot I think was from the other theme!

The #193 PR should sort it out, and I will release it shortly.

**Comment by rowanc1** [comment]
This is now deployed, to get the latest theme, you can:

```
myst clean --templates
myst start
```

![image](https://github.com/executablebooks/myst-theme/assets/913249/5006c379-ce20-4871-bcb9-4eb912ba89a2)
