### ISSUE TITLE
Small screen TOC is not keyboard navigable

### ISSUE THREAD

**Issue by stevejpurves** [executablebooks/myst-theme#228]
### Describe the bug

**context**
On a smaller screen, when I attempt to access the table of contents using the keyboard 

**expectation**
I expected to be able to open the TOC with the first item focussed and use the keyboard ot navigate the items.

**bug**
But instead the contents of the TOC does not get focus and nor does it respond to keyboard events, in fact the main article still has keyboard focus.

**problem**
This is an accessbility problem for keyboard users.

### Reproduce the bug

![LlDsjn65UO](https://github.com/executablebooks/myst-theme/assets/1473646/bc7cf454-3506-4a64-b435-79d38b59bbdd)

**Comment by rowanc1** [comment]
This has been fixed in #254.

![a11y-keyboardtoc](https://github.com/executablebooks/myst-theme/assets/913249/18093b88-4e46-4a13-a1c4-f0672126cbbc)
