### ISSUE TITLE
Dark mode selection does not persist during site navigation

### ISSUE THREAD

**Issue by fwkoch** [executablebooks/myst-theme#233]
Copied from here: https://github.com/executablebooks/mystmd/issues/585

If I activate dark mode on a page, then navigate to another page in the same MyST site, it reverts to light mode. I would expect dark mode selection to persist during site navigation.

**Comment by rowanc1** [comment]
This is broken in static exports, we need to update the dark mode to be based on local preferences rather than server side set cookies.

**Comment by rowanc1** [comment]
Duplicate of #319
