### ISSUE TITLE
Ability to set a custom "DefaultComponent" for Myst-to-react renderer

### ISSUE THREAD

**Issue by Carreau** [executablebooks/myst-theme#294]
### Context

It seem that by default if there is no node type for a renderer,  Myst-to-react will fallback to DefaultComponent (see MyST.tsx). The default is to wrap in div/span depending on wether the component contains children (or not), and recurse.

Unfortunately this does not seem easy to configure (it might be doable, but I'm nto familiar enough with react/js to figure out how)

### Proposal

Make the DefaultComponent hook configurable, either a separate configuration, or maybe a specific type in renderers ? 

```
renderers[node.type] ?? renderers['default'] ?? DefaultComponent
```

Happy to do it, but i'm not yet versed in JS/TSX, so you would have to bear with my crappy code.

### Tasks and updates

- [ ] decide if this need to be done
- [ ] how to have it done
- [ ] document

**Comment by rowanc1** [comment]
Thanks so much for your help on this @Carreau!!
