### ISSUE TITLE
File title not showing up in the toc when in an explicit first cell (e.g. with metadata)

### ISSUE THREAD

**Issue by nthiery** [executablebooks/myst-theme#304]
### Describe the bug

**context**
When the title of a file is within an explicit cell, e.g. because that cell will have some metadata:

```
---
... notebook front matter ...
---
+++ {"deletable": false}
# My file title
```

**expectation**

I still expect "My file title" to appear in the table of content on the web page, as if the file's body started directly with the title:
```
---
... notebook front matter ...
---
# My file title
```

**bug**

However the title `index-xxx` appears instead as title in the table of content.

**problem**

This prevents using metadata for the first cell. For teaching, I typically set that
first cell as readonly, or have some nbgrader metadata for that cell. Metadata
is also typically used for slideshow configuration.

### Reproduce the bug

See https://nicolas.thiery.name/Enseignement/Info111/myst/

### List your environment

```
> myst --version
v1.1.36
> python --version
Python 3.11.6
> cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.3 LTS"
```

**Comment by nthiery** [comment]
Oops; I hope I opened that issue on the correct project. Let me know if I should move it to

https://github.com/executablebooks/mystmd

**Comment by rowanc1** [comment]
@nthiery we have fixed this recently in MyST!

**Comment by nthiery** [comment]
Yeah, thank you!
