### ISSUE TITLE
Page rerenders on scroll

### ISSUE THREAD

**Issue by stevejpurves** [executablebooks/myst-theme#31]
### Describe the bug

**context**
When I do scroll up of down the page.

**expectation**
I expected React not to re-render the page

**bug**
But instead rerendering is happening, as confirmed by a console log message in development

**problem**
This is a problem as this re-rendering is unnecessary and can affect page performance.

### Reproduce the bug

1. run the theme in development
2. add a console.log message to a page
3. scroll and watch the console

**Comment by rowanc1** [comment]
Before:
![image](https://user-images.githubusercontent.com/913249/232981248-b63fb199-dcaf-40a3-8516-2fcdd64e9843.png)

After:
![image](https://user-images.githubusercontent.com/913249/232981111-589327db-f6a1-40e3-9685-0eab412df6aa.png)
