### ISSUE TITLE
"made with myst" link is broken

### ISSUE THREAD

**Issue by stevejpurves** [executablebooks/myst-theme#32]
### Describe the bug

**context**
The book theme has a sidebar/footer item that "Made with MyST" it links to the url: [https://myst-tools.org/made-with-myst](https://myst-tools.org/made-with-myst) but that link is broken.

**expectation**
I expected a page to load.

![image](https://user-images.githubusercontent.com/1473646/224282715-db6225a0-7214-498e-9aab-a0dae38e7806.png)

### Reproduce the bug

1. click on "Made with MyST" on a myst website

**Comment by rowanc1** [comment]
This now redirects to a tutorial!
